### ISSUE TITLE
Blocks are breaking the game

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Sharlottes/sharustry#10]
java.lang.NoSuchMethodError: 'int mindustry.world.meta.Attribute.ordinal()'
	at Sharustry.world.blocks.production.AttributeDrill$AttributeDrillBuild.buildConfiguration(AttributeDrill.java:127)
	at mindustry.ui.fragments.BlockConfigFragment.showConfig(BlockConfigFragment.java:57)
	at mindustry.input.InputHandler.tileTapped(InputHandler.java:947)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:505)
	at mindustry.input.DesktopInput.update(DesktopInput.java:280)
	at mindustry.core.Control.update(Control.java:532)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:165)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:153)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
	

java.lang.NoClassDefFoundError: mindustry/world/meta/values/FloorEfficiencyValue
	at Sharustry.world.blocks.production.AttributeDrill.lambda$setStats$8(AttributeDrill.java:60)
	at mindustry.ui.dialogs.ContentInfoDialog.lambda$show$1(ContentInfoDialog.java:73)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:68)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.FloorEfficiencyValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
	

	java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.SkillTurret.setStats(SkillTurret.java:40)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.dialogs.ResearchDialog$View.lambda$rebuild$10(ResearchDialog.java:486)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more

java.lang.NoSuchFieldError: whiteui
	at Sharustry.world.blocks.defense.MountSelection.buildTable(MountSelection.java:28)
	at Sharustry.world.blocks.defense.MultiTurret$MultiTurretBuild.buildConfiguration(MultiTurret.java:417)
	at mindustry.ui.fragments.BlockConfigFragment.showConfig(BlockConfigFragment.java:57)
	at mindustry.input.InputHandler.tileTapped(InputHandler.java:947)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:505)
	at mindustry.input.DesktopInput.update(DesktopInput.java:280)
	at mindustry.core.Control.update(Control.java:532)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:165)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:153)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

java.lang.NoSuchFieldError: whiteui
	at Sharustry.world.blocks.defense.MountSelection.buildTable(MountSelection.java:28)
	at Sharustry.world.blocks.defense.MultiTurret$MultiTurretBuild.buildConfiguration(MultiTurret.java:417)
	at mindustry.ui.fragments.BlockConfigFragment.showConfig(BlockConfigFragment.java:57)
	at mindustry.input.InputHandler.tileTapped(InputHandler.java:947)
	at mindustry.input.DesktopInput.pollInput(DesktopInput.java:505)
	at mindustry.input.DesktopInput.update(DesktopInput.java:280)
	at mindustry.core.Control.update(Control.java:532)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:174)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:165)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:153)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

java.lang.NoClassDefFoundError: mindustry/world/meta/values/AmmoListValue
	at Sharustry.world.blocks.defense.TemplatedTurret.setStats(TemplatedTurret.java:75)
	at Sharustry.world.blocks.defense.MultiTurret.setStats(MultiTurret.java:237)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:78)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:28)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)
Caused by: java.lang.ClassNotFoundException: mindustry.world.meta.values.AmmoListValue
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:36)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

I know nothing about programing, so I really hope anything in these crash reports is usefull

**Comment by Arthur-The-Ok** [comment]
Sorry for the issue, I forgot to  udate the mod.
