### ISSUE TITLE
Game doesn't like when I try to look at the Adapt Drill's description

### ISSUE THREAD

**Issue by Arthur-The-Ok** [Sharlottes/sharustry#12]
java.lang.NoSuchMethodError: 'mindustry.world.meta.StatValue mindustry.world.meta.StatValues.floorEfficiency(mindustry.world.blocks.environment.Floor, float, boolean)'
	at Sharustry.world.blocks.production.AttributeDrill.lambda$setStats$8(AttributeDrill.java:57)
	at mindustry.ui.dialogs.ContentInfoDialog.lambda$show$1(ContentInfoDialog.java:74)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:69)
	at acontent.ui.AdvancedContentInfoDialog.show(AdvancedContentInfoDialog.java:33)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:323)
	at arc.scene.Element$9.changed(Element.java:968)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:366)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:100)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:151)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by USMP-lancer** [comment]
yes, as of 135 it also crashes, but i get the feeling this mod is kinda dead

**Comment by Sharlottes** [comment]
fixed, be released soon
